services:
    nginx:
      container_name: nginx
      build:
        context: ./nginx
      command: nginx -g 'daemon off;'
      restart: unless-stopped
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.template
      environment:
        NGINX_PORT: ${NGINX_PORT}
      ports:
        - "80:${NGINX_PORT}"
      networks:
        rnp-net:

    fe:
      container_name: ${PROJECT_NAME}-fe
      build:
        context: ./fe
        dockerfile: Dockerfile
      command: npm run dev
      restart: unless-stopped
      volumes:
        - ./fe:/usr/fe
        - /usr/fe/node_modules
      networks:
        rnp-net:

    be:
      container_name: ${PROJECT_NAME}-be
      build:
        context: ./be
        dockerfile: Dockerfile
      command: npm run start:dev
      restart: unless-stopped
      volumes:
        - ./be:/usr/be
        - /usr/be/node_modules
      environment:
        NODE_ENV: dev
        POSTGRES_URL: ${POSTGRES_URL}
      networks:
        rnp-net:

    postgres:
      container_name: ${PROJECT_NAME}-db
      image: postgres
      restart: unless-stopped
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "5432:5432"
      networks:
        rnp-net:


volumes:
  postgres-data:

networks:
  rnp-net: