services:
    fe:
      container_name: ${PROJECT_NAME}-fe
      build:
        context: ./fe
        dockerfile: Dockerfile
      command: npm run dev
      restart: unless-stopped
      volumes:
        - ./fe:/usr/fe
        - /usr/fe/node_modules
      ports:
        - "3001:3001"
      networks:
        rnp-net:

    be:
      container_name: ${PROJECT_NAME}-be
      build:
        context: ./be
        dockerfile: Dockerfile
      command: npm run start:dev
      restart: unless-stopped
      volumes:
        - ./be:/usr/be
        - /usr/be/node_modules
      ports:
        - "3002:3002"
      environment:
        POSTGRES_URL: ${POSTGRES_URL}
      networks:
        rnp-net:

    postgres:
      container_name: ${PROJECT_NAME}-db
      image: postgres
      restart: unless-stopped
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DATABASE}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      networks:
        rnp-net:


volumes:
  postgres-data:

networks:
  rnp-net: